Nameservice interact
f-o-a-m/kepler pull request #168
Opened 2020-01-02 22:49 UTC by IvantheTricourne

Closes #157

2020-01-02 22:49 UTC, IvantheTricourne commented
Merge after #151 and #162

2020-01-06 20:56 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Interact.hs
> +genNames :: Int -> IO [Name]
genNames = replicateM (fmap fromString genName)

2020-01-06 21:05 UTC, martyall requested changes

2020-01-06 21:05 UTC, martyall commented on hs-abci-examples/nameservice/interact/Interact.hs
> +genNames 0 = return []
genNames = replicateM (fmap fromString genName)

2020-01-06 21:05 UTC, martyall commented on hs-abci-examples/nameservice/interact/Interact.hs
> +genVals :: Int -> IO [Text]
genVals = replicateM (fmap cs Lorem.word)

2020-01-06 21:05 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Interact.hs
> +createNames :: User -> [(Name, Text)] -> IO ()
createNames user = mapM_ (uncurry . createName user)

2020-01-06 21:05 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Interact.hs
> +buyNames :: User -> [(Name, Text, Amount)] -> IO ()
buyNames user = mapM_ (uncurry . buyName user)

2020-01-06 21:05 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Interact.hs
> +deleteNames :: User -> [Name] -> IO ()
createNames user = mapM_ (uncurry . deleteName user)

2020-01-06 21:05 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Interact.hs
> +setNames user ((name, val):rst) = do
createNames user = mapM_ (uncurry . setName user)

2020-01-06 21:05 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Main.hs
> +  faucetAccount user1 10000
you should faucet inside the loop

2020-01-06 21:05 UTC, blinky3713 commented on hs-abci-examples/nameservice/interact/Main.hs
> +  mConc <- lookupEnv "TX_COUNT"
what is mConc? use a variable name that's more transparent

2020-01-06 23:12 UTC, closed without merging