copy conduit
f-o-a-m/kepler pull request #17
Opened 2019-07-19 10:57 UTC by safareli

fix #14

2019-07-19 11:00 UTC, safareli commented on stack.yaml
> +extra-deps:
Without this changes I was getting:
```
/hs-abci-server/src/Network/ABCI/Wire.hs:30:1: error:
    Could not load module ‘Data.ProtoLens.Encoding.Bytes’
    it is a hidden module in the package ‘proto-lens-0.4.0.1’
    Use -v to see a list of the files searched for.
   |
30 | import           Data.ProtoLens.Encoding.Bytes (getVarInt, putVarInt,
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

2019-07-19 16:29 UTC, martyall requested changes
The copy paste code is fine, but you answer some of the questions about where things look like they could use improvement? For example in how we parse things, or where errors are handled /reported in a way which we could do better We want to turn those into issues.

2019-07-22 11:14 UTC, safareli commented
Regarding improvements, at this moment i don't see anything important, I guess once we start actually building some examples on top of it we would have better understanding and will see useful improvements.

2019-07-23 05:11 UTC, martyall approved these changes

2019-07-23 05:13 UTC, merged