all int64s wrapped for specific JSON parsing
f-o-a-m/kepler pull request #70
Opened 2019-09-19 00:12 UTC by charlescrain

2019-09-19 00:13 UTC, charlescrain commented
FYI the brittany formatter changed some of the files, LMK if its not a style you like.

2019-09-19 06:18 UTC, martyall requested changes

2019-09-19 06:18 UTC, blinky3713 commented on hs-abci-types/src/Network/ABCI/Types/Messages/FieldTypes.hs
> +{-# LANGUAGE GeneralizedNewtypeDeriving #-}
we should put this in the `package.yaml` file

2019-09-19 06:20 UTC, blinky3713 commented
How are you invoking this formatter? I don't see any kind of config file or `make` command.

2019-09-21 22:10 UTC, charlescrain commented
> How are you invoking this formatter? I don't see any kind of config file or `make` command.

It's the default formatter in hie-vscode

2019-09-21 23:16 UTC, charlescrain commented
I went through and fixed the formatting. I also wrote custom parsers where necessary. The parser for HexString now handles, Null and parsers it as an empty hexstring. Since its defined for use within this package it seemed like a good idea as it saves writing a bunch of custom parsers. Let me know if this doesn't work and I'll dive in and do the custom parsers.

2019-09-22 18:12 UTC, charlescrain commented
Found another problem with our encoding, we need to use `Base64` strings instead.

2019-09-24 16:04 UTC, martyall approved these changes

2019-09-24 16:53 UTC, merged