Messages parser
f-o-a-m/kepler pull request #98
Opened 2019-11-12 21:27 UTC by IvantheTricourne

2019-11-12 21:33 UTC, martyall requested changes

2019-11-12 21:33 UTC, blinky3713 commented on hs-abci-examples/nameservice/src/Nameservice/Modules/Token.hs
> +fromProtoAmountVal :: Word64 -> Amount
Why not just use Word64 for the `Amount` instead of `Int32`?

2019-11-12 21:33 UTC, blinky3713 commented on hs-abci-examples/nameservice/src/Nameservice/Modules/Nameservice/Messages.hs
> +fromProtoMsgSetName :: M.SetName -> Either Text MsgSetName
the `MsgSetName` prefix is internal, similarly with `MsgDeleteName` etc. Don't include them in the error messages

2019-11-12 21:33 UTC, blinky3713 commented on hs-abci-examples/nameservice/src/Nameservice/Modules/Nameservice/Messages.hs
> +nonNegativeAmount :: (Ord a, Num a) => a -> Either Text a
If you change to Word64 you don't need this

2019-11-12 21:49 UTC, martyall approved these changes

2019-11-13 15:42 UTC, IvantheTricourne commented
Closing in favor of #100

2019-11-13 15:42 UTC, closed without merging